version: '2'
services:
  web:
    build: .
    command: /bin/bash -c "rails db:migrate:reset db:seed && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/spacehack-app
    ports:
      - "3000:3000"
  thumbor:
    image: apsl/thumbor:latest
    volumes:
      - data:/data
    ports:
      - "8081:8000" 
    environment:
      - DETECTORS=['thumbor.detectors.feature_detector']
    networks:
      - app
volumes:
  data:
    driver: local
networks:
  app:
    driver: bridge